app:
    baseUrlForEvents: "https://kudago.com/public-api/v1.4"
    baseUrlForConvertValute: "http://localhost:4040"


api:
  client:
    reactive:
      enabled: false

spring:
  application:
    name: Fintech_Spring
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/homework_db
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace

thread:
  threadCount: 16

duration:
  delay: 10

server:
  port: 8080

