app:
  baseUrl: "https://kudago.com/public-api/v1.4"
  baseUrlForConvertValute: "http://localhost:4040/"
spring:
  application:
    name: Fintech_Spring



thread:
  count: 16

duration:
  delay: 10

server:
  port: 8080

