app:
  baseUrl: "https://cbr.ru/scripts"

spring:
  application:
    name: hw8

caching:
  spring:
    valuteListTTL: 3600000


resilience4j.circuitbreaker:
  instances:
    bankClient:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true


server:
  port: 4040